from typing import Protocol, Callable, Any, List
from typing import runtime_checkable

from openscada_lite.common.models.entities import Datapoint

@runtime_checkable
class DriverProtocol(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    def subscribe(self, datapoints: List[Datapoint]) -> None: ...
    def register_value_listener(self, callback: Callable) -> None: ...
    #Async because it publishes all the driver states (to know the available drivers)
    async def register_communication_status_listener(self, callback: Callable) -> None: ...
    def register_command_feedback(self, callback: Callable) -> None: ...
    async def send_command(self, tag_id: str, command: Any, command_id: str) -> None: ...

    @property
    def server_name(self) -> str: ...
    @property
    def is_connected(self) -> bool: ...