from typing import Protocol
from openscada_lite.common.models.dtos import RawTagUpdateMsg, CommandFeedbackMsg, DriverConnectStatus

class CommunicationListener(Protocol):
    async def on_raw_tag_update(self, msg: RawTagUpdateMsg): ...
    async def on_command_feedback(self, msg: CommandFeedbackMsg): ...
    async def on_driver_connect_status(self, msg: DriverConnectStatus): ...